### PR TITLE
Update Default Key Derivation Path

### PR DESCRIPTION
**Pull request by ProtocolCash**
- use /44'/145'/0' per standard, instead of zero path /44'/0'/0'

### CODE REVIEW

**Comment by ghost** [comment]
There is another file you need to change for the derivation path. As seen here:
https://github.com/ProtocolCash/bitcoinj-cash/pull/1/commits/a07d9e9d6a904bc1e33a5c78ac7e4bca59c8278c#diff-90caeeed6b111a1840eed8445740bd80

**Comment by ProtocolCash** [comment]
@pokkst thank-you. Change made.

**Comment by ghost** [comment]
Sick, this one looks good to go.

**Comment by imaginaryusername** [comment]
@Gitcash send 2 BCH to @ProtocolCash

**Comment by GitCash** [comment]
Hey **ProtocolCash**, user **imaginaryusername** tipped you **2000000 bits** in Bitcoin Cash ( ~ **$588** ).

*[Click here to claim it!](https://gitcash.io/claim/ProtocolCash)*

You can also add the "thumbs down" reaction to **imaginaryusername**'s comment above to prevent future tips.

**Pull request merged**
