### PR TITLE
Derivation path, CashAddr, Cash Account

### PR DESCRIPTION
**Pull request by pokkst**
This update to BitcoincashJ now includes:
- Standard derivation path m/44'/145'/0' for wallets, instead of m/0'
- CashAddr support by default with Wallet.currentReceiveAddress and Wallet.freshReceiveAddress
- Cash Account (https://cashaccount.info) sending support in SendRequest.to and SendRequest.emptyWallet

### CODE REVIEW

**Comment by ProtocolCash** [comment]
Can you cleanup the 100644 → 100755 non-changes?

Breaking this up into 3 pull requests would also be appreciated for ease of review.

Quick glance looks good otherwise!

**Comment by ghost** [comment]
The new commits were automatically added, and I thought I had git ignoring the non-changes, but I guess not. :/ Oops.

**Comment by ProtocolCash** [comment]
Two new pull requests for Cash Addresses and Key Derivation Path:
https://github.com/ProtocolCash/bitcoinj-cash/pull/3
https://github.com/ProtocolCash/bitcoinj-cash/pull/4

If you are you able to review these, that would be awesome. 
A clean pull for Cash Accounts is still needed to.

**Comment by ghost** [comment]
For Cash Accounts all you need to do is copy these files:

https://github.com/ProtocolCash/bitcoinj-cash/pull/1/commits/a07d9e9d6a904bc1e33a5c78ac7e4bca59c8278c#diff-3e4047888c4159a9a6a5f7b57dd7b698

https://github.com/ProtocolCash/bitcoinj-cash/pull/1/commits/a07d9e9d6a904bc1e33a5c78ac7e4bca59c8278c#diff-713decd43083dc81281ee791be11019f

https://github.com/ProtocolCash/bitcoinj-cash/pull/1/commits/feb3bc1031dcf8138eefc80bc0f4eecfae947d7b#diff-4da3d48ebbe24f1835196b0ec02c184e

and

https://github.com/ProtocolCash/bitcoinj-cash/pull/1/commits/feb3bc1031dcf8138eefc80bc0f4eecfae947d7b#diff-58383b731b8af9dec0bff66846c2b704

There might be a few other files you need to change in the tests area. It'll tell you when compiling.

I'd make a new PR rn but I'm busy doing stuff around the house.

**Pull request closed without merging**
