### PR TITLE
Make Cash Address the Default Address Format

### PR DESCRIPTION
**Pull request by ProtocolCash**
- move CashAddressType enum and private variable, and getLegacyVersion and getType functions from CashAddress to parent class Address
- rename addressType to cashAddressType and add Unknown to enum
- set cashAddressType in Address constructors
- add fromCashAddress and fromAddressString constructors to Address
- Overwrite toString on Address to return CashAddress format
- fix comment in CashAddressFactory
- update walletTemplate to use fromAddressString instead of fromBase58

### CODE REVIEW

**Comment by ghost** [comment]
You didn't need to add so many lines. You simply could have updated the freshAddress() and currentAddress() base method in Wallet.java like I did.

**Comment by ProtocolCash** [comment]
That would work for the wallet class, yes. But not for anything using the library to construct an Address object outside of the wallet. The Address level seemed the most logical, as it has no specific dependency to be represented as base58, and most lines are moving CashAddress code to the Address parent class.

This PR attempts to make the logic change at a place in the call stack where it would have the most impact on the default appearance of addresses, while trying to avoid breaking any software using base58 inputs. 

Software referencing bitcoinj-cash need only be updated if it is expecting base58 output from Account.toString() and replace any Address.fromBase58() calls with Address.fromAddressString() to accept cash address format address input.

**Comment by ProtocolCash** [comment]
@pokkst Definitely open to your looking at your alternative more closely if you create a new branch with only those changes. It's unfortunately very hard to review your existing branch.

**Comment by ghost** [comment]
Mine's pretty simple and more of which for sending or receiving. I wrote it up fairly quickly.

You can take a legacy address and convert it to a CashAddress using CashAddressFactory.

I simply changed the base methods in Wallet.java for getting the currentReceiveAddress and freshReceiveAddress, and to get the CashAddr as a String you just called toString() instead of toBase58 in Address.java or whatever it extends from.

https://github.com/pokkst/bitcoincashj/blob/cash-0.14/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L403

https://github.com/pokkst/bitcoincashj/blob/cash-0.14/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L469

**Comment by magmahindenburg** [comment]
> Overwrite toString on Address to return CashAddress format

This would make lots of existing code break if using this library since the expected output would be the legacy address. If I used this library I would revert this.

Edit: It would not break compilation, but cause other problems down the line upon execution.

**Comment by ProtocolCash** [comment]
Points taken. Will consider a PR that moves CashAddress functions to Address, but leaves the legacy address support as is.

I'd rather tear out base58 entirely, and it might be a positive to force apps using this library to stop using legacy addresses and then just converting to cashaddr for display. But, the main point in maintaining the library is for dependant apps. So, closing.

**Pull request closed without merging**
